package de.fhdo.pflegetagebuch.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.time.LocalDateTime;
import java.util.UUID;

@DynamoDBTable(tableName = "Task")
public class Task {
    protected UUID id;
    protected String name;
    protected LocalDateTime completionDate;
    protected String supportNeeded;
    protected String healthStatus;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public UUID getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "completionDate")
    public LocalDateTime getCompletionDate() {
        return completionDate;
    }

    public void setCompletionDate(LocalDateTime completionDate) {
        this.completionDate = completionDate;
    }

    @DynamoDBAttribute(attributeName = "supportNeeded")
    public SupportNeeded getSupportNeeded() {
        return SupportNeeded.valueOf(supportNeeded);
    }

    public void setSupportNeeded(SupportNeeded supportNeeded) {
        this.supportNeeded = supportNeeded.toString();
    }

    @DynamoDBAttribute(attributeName = "healthStatus")
    public HealthStatus getHealthStatus() {
        return HealthStatus.valueOf(healthStatus);
    }

    public void setHealthStatus(HealthStatus healthStatus) {
        this.healthStatus = healthStatus.toString();
    }
}
